// Auto-generated from Nomo Dark Icon Theme (be5invis/vscode-iconset)
// Do not edit manually

export const DEFAULT_FILE_ICON = '/icons/nomo-dark/file.svg';
export const DEFAULT_FOLDER_ICON = '/icons/nomo-dark/folder.close.svg';
export const DEFAULT_FOLDER_OPEN_ICON = '/icons/nomo-dark/folder.open.svg';

export const fileExtensionMap: Record<string, string> = {
  'dockerfile': '/icons/nomo-dark/config.docker.svg',
  'ino': '/icons/nomo-dark/file.ino.svg',
  'json': '/icons/nomo-dark/file.json.svg',
  'c': '/icons/nomo-dark/file.c.svg',
  'cu': '/icons/nomo-dark/config.cuda.svg',
  'cuh': '/icons/nomo-dark/config.cudaH.svg',
  'h': '/icons/nomo-dark/file.h.svg',
  'hpp': '/icons/nomo-dark/file.h.svg',
  'hxx': '/icons/nomo-dark/file.h.svg',
  'hh': '/icons/nomo-dark/file.h.svg',
  'cpp': '/icons/nomo-dark/file.cpp.svg',
  'cc': '/icons/nomo-dark/file.cpp.svg',
  'cxx': '/icons/nomo-dark/file.cpp.svg',
  'd': '/icons/nomo-dark/file.d.svg',
  'di': '/icons/nomo-dark/file.d.svg',
  'js': '/icons/nomo-dark/file.js.svg',
  'mjs': '/icons/nomo-dark/file.js.svg',
  'html': '/icons/nomo-dark/file.html.svg',
  'htm': '/icons/nomo-dark/file.html.svg',
  'css': '/icons/nomo-dark/file.css.svg',
  'styl': '/icons/nomo-dark/file.stylus.svg',
  'sass': '/icons/nomo-dark/file.sass.svg',
  'scss': '/icons/nomo-dark/file.sass.svg',
  'less': '/icons/nomo-dark/file.less.svg',
  'md': '/icons/nomo-dark/file.markdown.svg',
  'cs': '/icons/nomo-dark/file.cs.svg',
  'fs': '/icons/nomo-dark/file.fs.svg',
  'feature': '',
  'go': '/icons/nomo-dark/file.go.svg',
  'lua': '/icons/nomo-dark/file.lua.svg',
  'rs': '/icons/nomo-dark/file.rust.svg',
  'py': '/icons/nomo-dark/file.python.svg',
  'pyc': '/icons/nomo-dark/file.python.svg',
  'pyo': '/icons/nomo-dark/file.python.svg',
  'pyd': '/icons/nomo-dark/file.python.svg',
  'pyw': '/icons/nomo-dark/file.python.svg',
  'ruo': '/icons/nomo-dark/file.ruota.svg',
  'rb': '/icons/nomo-dark/file.ruby.svg',
  'jl': '/icons/nomo-dark/file.julia.svg',
  'php': '/icons/nomo-dark/file.php.svg',
  'haxe': '/icons/nomo-dark/file.haxe.svg',
  'hxml': '/icons/nomo-dark/file.haxe.svg',
  'java': '/icons/nomo-dark/file.java.svg',
  'ts': '/icons/nomo-dark/file.ts.svg',
  'd.ts': '/icons/nomo-dark/file.d.ts.svg',
  'vue': '/icons/nomo-dark/file.vue.svg',
  'xml': '/icons/nomo-dark/file.xml.svg',
  'coffee': '/icons/nomo-dark/file.coffee.svg',
  'litcoffee': '/icons/nomo-dark/file.coffee.svg',
  'ex': '/icons/nomo-dark/file.elixir.svg',
  'exs': '/icons/nomo-dark/file.elixir.svg',
  'clj': '/icons/nomo-dark/file.clojure.svg',
  'jsx': '/icons/nomo-dark/file.jsx.svg',
  'gql': '/icons/nomo-dark/file.gql.svg',
  'tsx': '/icons/nomo-dark/file.tsx.svg',
  'toml': '/icons/nomo-dark/file.toml.svg',
  'yml': '/icons/nomo-dark/file.yaml.svg',
  'yaml': '/icons/nomo-dark/file.yaml.svg',
  'ss': '/icons/nomo-dark/file.scheme.svg',
  'scm': '/icons/nomo-dark/file.scheme.svg',
  'lisp': '/icons/nomo-dark/file.lisp.svg',
  'lsp': '/icons/nomo-dark/file.lisp.svg',
  'l': '/icons/nomo-dark/file.lisp.svg',
  'cl': '/icons/nomo-dark/file.lisp.svg',
  'fasl': '/icons/nomo-dark/file.lisp.svg',
  'el': '/icons/nomo-dark/file.elisp.svg',
  'elc': '/icons/nomo-dark/file.elisp.svg',
  'ptl': '/icons/nomo-dark/file.ptl.svg',
  'patel': '/icons/nomo-dark/file.ptl.svg',
  'hs': '/icons/nomo-dark/file.haskell.svg',
  'lhs': '/icons/nomo-dark/file.haskell.svg',
  'idr': '/icons/nomo-dark/file.idris.svg',
  'v': '/icons/nomo-dark/file.coq.svg',
  'ml': '/icons/nomo-dark/file.ml.svg',
  'mli': '/icons/nomo-dark/file.ml.svg',
  'mll': '/icons/nomo-dark/file.ml.svg',
  'fst': '/icons/nomo-dark/file.fst.svg',
  'sats': '/icons/nomo-dark/file.ats.svg',
  'dats': '/icons/nomo-dark/file.ats.svg',
  'pro': '/icons/nomo-dark/file.prolog.svg',
  'P': '/icons/nomo-dark/file.prolog.svg',
  'elm': '/icons/nomo-dark/file.elm.svg',
  'purs': '/icons/nomo-dark/file.purescript.svg',
  'slim': '/icons/nomo-dark/file.slim.svg',
  'skim': '/icons/nomo-dark/file.slim.svg',
  'erl': '/icons/nomo-dark/file.erlang.svg',
  'swift': '/icons/nomo-dark/file.swift.svg',
  'tex': '/icons/nomo-dark/file.tex.svg',
  'vb': '/icons/nomo-dark/file.vb.svg',
  'mk': '/icons/nomo-dark/config.makefile.svg',
  'make': '/icons/nomo-dark/config.makefile.svg',
  'jade': '/icons/nomo-dark/file.jade.svg',
  'pug': '/icons/nomo-dark/file.jade.svg',
  'scala': '/icons/nomo-dark/file.scala.svg',
  'js.map': '/icons/nomo-dark/file.sourcemap.svg',
  'css.map': '/icons/nomo-dark/file.sourcemap.svg',
  'sh': '/icons/nomo-dark/file.shell.svg',
  'zsh': '/icons/nomo-dark/file.shell.svg',
  'bash': '/icons/nomo-dark/file.shell.svg',
  'fish': '/icons/nomo-dark/file.shell.svg',
  'elv': '/icons/nomo-dark/file.shell.svg',
  'bat': '/icons/nomo-dark/file.shell.svg',
  'cmd': '/icons/nomo-dark/file.shell.svg',
  'txt': '/icons/nomo-dark/file.text.svg',
  'bmp': '/icons/nomo-dark/file.image.svg',
  'jpg': '/icons/nomo-dark/file.image.svg',
  'jpeg': '/icons/nomo-dark/file.image.svg',
  'gif': '/icons/nomo-dark/file.image.svg',
  'png': '/icons/nomo-dark/file.image.svg',
  'svg': '/icons/nomo-dark/file.image.svg',
  'tif': '/icons/nomo-dark/file.image.svg',
  'tiff': '/icons/nomo-dark/file.image.svg',
  'psd': '/icons/nomo-dark/file.image.svg',
  'psb': '/icons/nomo-dark/file.image.svg',
  'ttf': '/icons/nomo-dark/file.font.svg',
  'otf': '/icons/nomo-dark/file.font.svg',
  'woff': '/icons/nomo-dark/file.font.svg',
  'woff2': '/icons/nomo-dark/file.font.svg',
  'sfd': '/icons/nomo-dark/file.font.svg',
  'eot': '/icons/nomo-dark/file.font.svg',
  'otd': '/icons/nomo-dark/file.json.svg',
  'bin': '/icons/nomo-dark/file.binary.svg',
  'exe': '/icons/nomo-dark/file.exe.svg',
  'dll': '/icons/nomo-dark/file.lib.svg',
  'lib': '/icons/nomo-dark/file.lib.svg',
  'o': '/icons/nomo-dark/file.binary.svg',
  'a': '/icons/nomo-dark/file.lib.svg',
  'so': '/icons/nomo-dark/file.lib.svg',
  'zip': '/icons/nomo-dark/file.zip.svg',
  'tar': '/icons/nomo-dark/file.zip.svg',
  'tgz': '/icons/nomo-dark/file.zip.svg',
  'gz': '/icons/nomo-dark/file.zip.svg',
  'xz': '/icons/nomo-dark/file.zip.svg',
  'bzip2': '/icons/nomo-dark/file.zip.svg',
  '7z': '/icons/nomo-dark/file.zip.svg',
  'rar': '/icons/nomo-dark/file.zip.svg',
  'hbs': '/icons/nomo-dark/file.handlebars.svg',
  'ps1': '/icons/nomo-dark/file.powershell.svg',
  'tests.ps1': '/icons/nomo-dark/file.pester.svg',
  'test.ps1': '/icons/nomo-dark/file.pester.svg',
  'cer': '/icons/nomo-dark/file.crt.svg',
  'cert': '/icons/nomo-dark/file.crt.svg',
  'crt': '/icons/nomo-dark/file.crt.svg',
  'der': '/icons/nomo-dark/file.crt.svg',
  'key': '/icons/nomo-dark/file.key.svg',
  'pem': '/icons/nomo-dark/file.crt.svg',
  'cr': '/icons/nomo-dark/file.cr.svg',
  'ecr': '/icons/nomo-dark/file.cr.svg',
};

export const fileNameMap: Record<string, string> = {
  'package.json': '/icons/nomo-dark/config.npm.svg',
  '.npmignore': '/icons/nomo-dark/config.npm.svg',
  '.npmrc': '/icons/nomo-dark/config.npm.svg',
  '.esformatter': '/icons/nomo-dark/config.format.svg',
  '.clang-format': '/icons/nomo-dark/config.format.svg',
  '.tfignore': '/icons/nomo-dark/config.vs.svg',
  '.vscodeignore': '/icons/nomo-dark/config.vs.svg',
  '.gitignore': '/icons/nomo-dark/config.git.svg',
  '.gitattributes': '/icons/nomo-dark/config.git.svg',
  '.travis.yml': '/icons/nomo-dark/config.travis.svg',
  'appveyor.yml': '/icons/nomo-dark/config.appveyor.svg',
  'licence': '/icons/nomo-dark/config.license.svg',
  'license': '/icons/nomo-dark/config.license.svg',
  'licence.md': '/icons/nomo-dark/config.license.svg',
  'license.md': '/icons/nomo-dark/config.license.svg',
  'copying': '/icons/nomo-dark/config.license.svg',
  '.editorconfig': '/icons/nomo-dark/config.editorconfig.svg',
  'readme.md': '/icons/nomo-dark/file.markdown.svg',
  'makefile': '/icons/nomo-dark/config.makefile.svg',
  'readme': '/icons/nomo-dark/file.text.svg',
  'install': '/icons/nomo-dark/file.text.svg',
  'releases': '/icons/nomo-dark/file.text.svg',
  '.bowerrc': '/icons/nomo-dark/config.bower.svg',
  'bower.json': '/icons/nomo-dark/config.bower.svg',
  'dockerfile': '/icons/nomo-dark/config.docker.svg',
  'dub.json': '/icons/nomo-dark/config.dub.svg',
  'dub.sdl': '/icons/nomo-dark/config.dub.svg',
  'dub.selections.json': '/icons/nomo-dark/config.dub.svg',
  'gruntfile': '/icons/nomo-dark/config.grunt.svg',
  'gruntfile.js': '/icons/nomo-dark/config.grunt.svg',
  'gulpfile': '/icons/nomo-dark/config.gulp.svg',
  'gulpfile.js': '/icons/nomo-dark/config.gulp.svg',
  'gulpfile.babel.js': '/icons/nomo-dark/config.gulp.svg',
  '.eslintrc': '/icons/nomo-dark/config.eslint.svg',
  '.eslintrc.js': '/icons/nomo-dark/config.eslint.svg',
  '.eslintrc.json': '/icons/nomo-dark/config.eslint.svg',
  '.eslintrc.yaml': '/icons/nomo-dark/config.eslint.svg',
  '.eslintrc.yml': '/icons/nomo-dark/config.eslint.svg',
  '.eslintignore': '/icons/nomo-dark/config.eslint.svg',
  '.babelrc': '/icons/nomo-dark/config.babel.svg',
  'yarn.lock': '/icons/nomo-dark/config.yarn.svg',
};

export const folderNameMap: Record<string, string> = {
  '.vscode': '/icons/nomo-dark/folder.vs.close.svg',
  '.git': '/icons/nomo-dark/folder.git.close.svg',
  'spec': '/icons/nomo-dark/folder.test.close.svg',
  'test': '/icons/nomo-dark/folder.test.close.svg',
  'tests': '/icons/nomo-dark/folder.test.close.svg',
  '__tests__': '/icons/nomo-dark/folder.test.close.svg',
  'node_modules': '/icons/nomo-dark/folder.js.close.svg',
  'build': '/icons/nomo-dark/folder.dist.close.svg',
  'bin': '/icons/nomo-dark/folder.dist.close.svg',
  '.bin': '/icons/nomo-dark/folder.dist.close.svg',
  'dist': '/icons/nomo-dark/folder.dist.close.svg',
  'deploy': '/icons/nomo-dark/folder.dist.close.svg',
  'src': '/icons/nomo-dark/folder.src.close.svg',
  'include': '/icons/nomo-dark/folder.include.close.svg',
  'source': '/icons/nomo-dark/folder.src.close.svg',
  'lib': '/icons/nomo-dark/folder.lib.close.svg',
  'typings': '/icons/nomo-dark/folder.ts.close.svg',
  'types': '/icons/nomo-dark/folder.ts.close.svg',
};

export const folderNameOpenMap: Record<string, string> = {
  '.vscode': '/icons/nomo-dark/folder.vs.open.svg',
  '.git': '/icons/nomo-dark/folder.git.open.svg',
  'spec': '/icons/nomo-dark/folder.test.open.svg',
  'test': '/icons/nomo-dark/folder.test.open.svg',
  'tests': '/icons/nomo-dark/folder.test.open.svg',
  '__tests__': '/icons/nomo-dark/folder.test.open.svg',
  'node_modules': '/icons/nomo-dark/folder.js.open.svg',
  'build': '/icons/nomo-dark/folder.dist.open.svg',
  'bin': '/icons/nomo-dark/folder.dist.open.svg',
  '.bin': '/icons/nomo-dark/folder.dist.open.svg',
  'dist': '/icons/nomo-dark/folder.dist.open.svg',
  'deploy': '/icons/nomo-dark/folder.dist.open.svg',
  'src': '/icons/nomo-dark/folder.src.open.svg',
  'include': '/icons/nomo-dark/folder.include.open.svg',
  'source': '/icons/nomo-dark/folder.src.open.svg',
  'lib': '/icons/nomo-dark/folder.lib.open.svg',
  'typings': '/icons/nomo-dark/folder.ts.open.svg',
  'types': '/icons/nomo-dark/folder.ts.open.svg',
};

export function getNomoFileIcon(fileName: string): string {
  const lower = fileName.toLowerCase();
  if (fileNameMap[lower]) return fileNameMap[lower];
  const ext = lower.includes('.') ? lower.slice(lower.lastIndexOf('.') + 1) : lower;
  if (fileExtensionMap[ext]) return fileExtensionMap[ext];
  return DEFAULT_FILE_ICON;
}

export function getNomoFolderIcon(folderName: string, isOpen: boolean): string {
  const lower = folderName.toLowerCase();
  const map = isOpen ? folderNameOpenMap : folderNameMap;
  return map[lower] || (isOpen ? DEFAULT_FOLDER_OPEN_ICON : DEFAULT_FOLDER_ICON);
}
