import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// ───────────────────────────────────────────────
// Language Map for Monaco Editor
// ───────────────────────────────────────────────

const EXTENSION_MAP: Record<string, string> = {
  // JavaScript / TypeScript
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  dts: 'typescript',

  // Web / Markup
  html: 'html',
  htm: 'html',
  xhtml: 'html',
  css: 'css',
  scss: 'scss',
  sass: 'scss',
  less: 'less',
  styl: 'stylus',
  stylus: 'stylus',
  postcss: 'css',
  pcss: 'css',
  vue: 'html',
  svelte: 'html',
  ejs: 'html',
  hbs: 'handlebars',
  handlebars: 'handlebars',
  pug: 'pug',
  jade: 'pug',
  njk: 'html',
  twig: 'twig',
  liquid: 'liquid',
  mustache: 'html',

  // Data / Config / Serialisation
  json: 'json',
  jsonc: 'json',
  json5: 'json',
  yaml: 'yaml',
  yml: 'yaml',
  xml: 'xml',
  xsd: 'xml',
  xsl: 'xml',
  xslt: 'xml',
  svg: 'xml',
  plist: 'xml',
  ini: 'ini',
  toml: 'ini',
  cfg: 'ini',
  conf: 'ini',
  config: 'ini',
  properties: 'ini',
  env: 'ini',
  editorconfig: 'ini',
  npmrc: 'ini',
  yarnrc: 'ini',
  npmignore: 'plaintext',
  yarnignore: 'plaintext',
  dockerignore: 'plaintext',
  gitignore: 'plaintext',
  gitattributes: 'plaintext',
  gitmodules: 'plaintext',
  htaccess: 'plaintext',
  apacheconf: 'plaintext',
  nginxconf: 'plaintext',
  htpasswd: 'plaintext',
  csv: 'plaintext',
  tsv: 'plaintext',
  lock: 'plaintext',
  'tsbuildinfo': 'json',

  // Python
  py: 'python',
  pyi: 'python',
  pyc: 'plaintext',
  pyd: 'plaintext',
  pyo: 'plaintext',
  pyw: 'python',
  pyx: 'python',
  pxd: 'python',
  pxi: 'python',
  ipynb: 'json',

  // Rust
  rs: 'rust',

  // Go
  go: 'go',
  mod: 'go',
  sum: 'plaintext',

  // Java / JVM
  java: 'java',
  class: 'plaintext',
  jar: 'plaintext',
  kt: 'kotlin',
  kts: 'kotlin',
  scala: 'scala',
  sc: 'scala',
  groovy: 'plaintext',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  edn: 'clojure',

  // C / C++ / C# / .NET
  c: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  h: 'c',
  hpp: 'cpp',
  hh: 'cpp',
  hxx: 'cpp',
  inl: 'cpp',
  cs: 'csharp',
  csx: 'csharp',
  fs: 'fsharp',
  fsi: 'fsharp',
  fsx: 'fsharp',
  fsscript: 'fsharp',
  vb: 'vb',
  vbs: 'vb',
  il: 'plaintext',
  asm: 'plaintext',
  s: 'plaintext',

  // Mobile / Apple
  swift: 'swift',
  m: 'objective-c',
  mm: 'cpp',

  // Google / Flutter
  dart: 'dart',

  // Scripting / Shell
  php: 'php',
  phtml: 'php',
  php3: 'php',
  php4: 'php',
  php5: 'php',
  phps: 'php',
  rb: 'ruby',
  rbx: 'ruby',
  rjs: 'ruby',
  gemspec: 'ruby',
  rakefile: 'ruby',
  rake: 'ruby',
  lua: 'lua',
  pl: 'perl',
  pm: 'perl',
  t: 'perl',
  pod: 'perl',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  fish: 'shell',
  csh: 'shell',
  tcsh: 'shell',
  ksh: 'shell',
  ps1: 'powershell',
  psm1: 'powershell',
  psd1: 'powershell',
  ps1xml: 'powershell',
  psc1: 'powershell',
  pssc: 'powershell',
  cmd: 'bat',
  bat: 'bat',
  nt: 'bat',
  reg: 'plaintext',
  awk: 'plaintext',
  sed: 'plaintext',

  // Other languages
  r: 'r',
  rd: 'r',
  rdata: 'r',
  rds: 'r',
  rmd: 'markdown',
  julia: 'julia',
  jl: 'julia',
  hs: 'plaintext',
  lhs: 'plaintext',
  erl: 'erlang',
  hrl: 'erlang',
  ex: 'elixir',
  exs: 'elixir',
  eex: 'elixir',
  leex: 'elixir',
  heex: 'elixir',
  elm: 'plaintext',
  purescript: 'plaintext',
  purs: 'plaintext',
  idris: 'plaintext',
 idr: 'plaintext',
  crystal: 'plaintext',
  cr: 'plaintext',
  nim: 'plaintext',
  nims: 'plaintext',
  nimble: 'plaintext',
  zig: 'plaintext',
  v: 'plaintext',
  vlang: 'plaintext',
  wren: 'plaintext',
  vala: 'plaintext',
  genie: 'plaintext',
  gs: 'plaintext',
  d: 'plaintext',
  di: 'plaintext',
  ada: 'plaintext',
  adb: 'plaintext',
  ads: 'plaintext',
  fortran: 'plaintext',
  f: 'plaintext',
  for: 'plaintext',
  f90: 'plaintext',
  f95: 'plaintext',
  f03: 'plaintext',
  f08: 'plaintext',
  cobol: 'plaintext',
  cbl: 'plaintext',
  cob: 'plaintext',
  copy: 'plaintext',
  coffee: 'coffeescript',
  litcoffee: 'coffeescript',
  pas: 'pascal',
  pp: 'pascal',
  inc: 'pascal',
  ml: 'plaintext',
  mli: 'plaintext',
  re: 'plaintext',
  rei: 'plaintext',
  res: 'plaintext',
  resi: 'plaintext',
  tl: 'plaintext',
  tla: 'plaintext',

  // WebAssembly
  wasm: 'plaintext',
  wat: 'plaintext',

  // SQL / Database
  sql: 'sql',
  sqlite: 'sql',
  sqlite3: 'sql',
  mysql: 'sql',
  pgsql: 'sql',
  plsql: 'sql',
  tsql: 'sql',
  mssql: 'sql',
  oracle: 'sql',
  cql: 'sql',
  hql: 'sql',
  ddl: 'sql',
  dml: 'sql',

  // GraphQL
  graphql: 'graphql',
  gql: 'graphql',

  // Protocol Buffers / gRPC
  proto: 'protobuf',
  protobuf: 'protobuf',
  pb: 'plaintext',

  // Template / Build
  cmake: 'plaintext',
  mak: 'plaintext',
  mk: 'plaintext',
  gnumakefile: 'plaintext',
  gradle: 'plaintext',
  jenkinsfile: 'plaintext',
  jcl: 'plaintext',
  bazel: 'plaintext',
  bzl: 'plaintext',
  build: 'plaintext',
  workspace: 'plaintext',
  buck: 'plaintext',
  pants: 'plaintext',
  justfile: 'plaintext',
  just: 'plaintext',

  // Docker / Container
  dockerfile: 'dockerfile',
  containerfile: 'dockerfile',

  // CI / CD
  travis: 'yaml',
  appveyor: 'yaml',
  circleci: 'yaml',
  gitlabci: 'yaml',
  github: 'yaml',
  workflow: 'yaml',
  action: 'yaml',

  // Ansible / Terraform / Cloud
  ansible: 'yaml',
  playbook: 'yaml',
  tf: 'plaintext',
  tfvars: 'plaintext',
  hcl: 'hcl',
  nomad: 'hcl',
  packer: 'json',
  vagrantfile: 'ruby',

  // Kubernetes
  k8s: 'yaml',
  kube: 'yaml',
  helmfile: 'yaml',

  // Markup / Documentation
  md: 'markdown',
  mdx: 'markdown',
  mkd: 'markdown',
  mkdn: 'markdown',
  markdown: 'markdown',
  rst: 'plaintext',
  rest: 'plaintext',
  tex: 'plaintext',
  latex: 'plaintext',
  ltx: 'plaintext',
  ctx: 'plaintext',
  cls: 'plaintext',
  sty: 'plaintext',
  bib: 'plaintext',
  dtx: 'plaintext',
  ins: 'plaintext',
  org: 'plaintext',
  adoc: 'plaintext',
  asciidoc: 'plaintext',
  asc: 'plaintext',
  creole: 'plaintext',
  mediawiki: 'plaintext',
  wiki: 'plaintext',
  wikitext: 'plaintext',

  // Log / Text
  log: 'plaintext',
  trace: 'plaintext',
  out: 'plaintext',
  stdout: 'plaintext',
  stderr: 'plaintext',
  dump: 'plaintext',
  stackdump: 'plaintext',
  crash: 'plaintext',

  // Diff / Patch
  diff: 'plaintext',
  patch: 'plaintext',

  // Fonts / Assets (plaintext binary descriptors)
  woff: 'plaintext',
  woff2: 'plaintext',
  ttf: 'plaintext',
  otf: 'plaintext',
  eot: 'plaintext',

  // Certificates / Keys
  pem: 'plaintext',
  crt: 'plaintext',
  cer: 'plaintext',
  der: 'plaintext',
  key: 'plaintext',
  pub: 'plaintext',
  p12: 'plaintext',
  pfx: 'plaintext',
  csr: 'plaintext',
  crl: 'plaintext',
  srl: 'plaintext',
  ssh: 'plaintext',
  gnupg: 'plaintext',
  gpg: 'plaintext',
  sig: 'plaintext',
  sign: 'plaintext',
  keystore: 'plaintext',
  jks: 'plaintext',

  // Archives (treated as plaintext since we can't edit binary)
  zip: 'plaintext',
  tar: 'plaintext',
  gz: 'plaintext',
  tgz: 'plaintext',
  bz2: 'plaintext',
  xz: 'plaintext',
  txz: 'plaintext',
  lz: 'plaintext',
  lzma: 'plaintext',
  lzo: 'plaintext',
  rz: 'plaintext',
  sz: 'plaintext',
  zst: 'plaintext',
  br: 'plaintext',
  lz4: 'plaintext',
  rar: 'plaintext',
  '7z': 'plaintext',
  cab: 'plaintext',
  iso: 'plaintext',
  dmg: 'plaintext',
  pkg: 'plaintext',
  deb: 'plaintext',
  rpm: 'plaintext',
  apk: 'plaintext',
  ipa: 'plaintext',
  xap: 'plaintext',
  snap: 'plaintext',
  flatpak: 'plaintext',
  appimage: 'plaintext',
  nupkg: 'plaintext',
  whl: 'plaintext',
  egg: 'plaintext',
  gem: 'plaintext',

  // Documents (read-only plaintext view)
  pdf: 'plaintext',
  doc: 'plaintext',
  docx: 'plaintext',
  dot: 'plaintext',
  dotx: 'plaintext',
  xls: 'plaintext',
  xlsx: 'plaintext',
  xlsm: 'plaintext',
  xlsb: 'plaintext',
  xltx: 'plaintext',
  ppt: 'plaintext',
  pptx: 'plaintext',
  potx: 'plaintext',
  ppsx: 'plaintext',
  odt: 'plaintext',
  ods: 'plaintext',
  odp: 'plaintext',
  rtf: 'plaintext',
  txt: 'plaintext',
  text: 'plaintext',
  me: 'plaintext',
  ics: 'plaintext',
  vcf: 'plaintext',
  abnf: 'plaintext',

  // Design / Creative
  psd: 'plaintext',
  ai: 'plaintext',
  eps: 'plaintext',
  indd: 'plaintext',
  aep: 'plaintext',
  prproj: 'plaintext',
  fla: 'plaintext',
  sketch: 'plaintext',
  fig: 'plaintext',
  xd: 'plaintext',
  c4d: 'plaintext',
  blend: 'plaintext',
  ma: 'plaintext',
  mb: 'plaintext',
  max: 'plaintext',
  '3ds': 'plaintext',
  obj: 'plaintext',
  fbx: 'plaintext',
  dae: 'xml',
  gltf: 'json',
  glb: 'plaintext',
  stl: 'plaintext',
  ply: 'plaintext',
  step: 'plaintext',
  stp: 'plaintext',
  iges: 'plaintext',
  igs: 'plaintext',

  // CAD / Engineering
  dwg: 'plaintext',
  dxf: 'plaintext',
  dwf: 'plaintext',
  dgn: 'plaintext',

  // Game Dev
  unity: 'yaml',
  prefab: 'yaml',
  mat: 'yaml',
  meta: 'yaml',
  asset: 'yaml',
  anim: 'yaml',
  controller: 'yaml',
  physmaterial: 'yaml',
  inputactions: 'json',
  renderpipeline: 'json',
  uxml: 'xml',
  uss: 'css',
  csproj: 'xml',
  sln: 'plaintext',
  vbproj: 'xml',
  vcproj: 'xml',
  vcxproj: 'xml',
  props: 'xml',
  targets: 'xml',
  nuspec: 'xml',

  // iOS / macOS specific
  storyboard: 'xml',
  xib: 'xml',
  strings: 'plaintext',
  xcconfig: 'plaintext',
  pbxproj: 'plaintext',
  bridgingheader: 'c',
  modulemap: 'plaintext',
  podspec: 'ruby',
  cartfile: 'plaintext',
  resolved: 'plaintext',
  entitlements: 'xml',
  provisioningprofile: 'plaintext',
  mobileprovision: 'plaintext',
  appiconset: 'json',
  imageset: 'json',
  launchimage: 'json',
  launchscreen: 'xml',
  appex: 'plaintext',
  dSYM: 'plaintext',

  // Android specific
  iml: 'xml',
  pro: 'plaintext',
  proguard: 'plaintext',
  aar: 'plaintext',
  aidl: 'java',
  renderscript: 'c',
  rsh: 'c',
  ninepatch: 'png',
  webp: 'webp',

  // Windows specific
  rc: 'plaintext',
  resx: 'xml',
  resw: 'xml',
  settings: 'xml',
  manifest: 'xml',
  sxs: 'xml',
  wix: 'xml',
  wixproj: 'xml',
  wxs: 'xml',
  wxi: 'xml',
  wxl: 'xml',
  nsi: 'plaintext',
  nsh: 'plaintext',
  iss: 'plaintext',
  inno: 'plaintext',
  inf: 'plaintext',
  sys: 'plaintext',
  drv: 'plaintext',
  ocx: 'plaintext',
  acm: 'plaintext',
  mui: 'plaintext',
  themepack: 'plaintext',
  deskthemepack: 'plaintext',
  msstyles: 'plaintext',
  cur: 'plaintext',
  ani: 'plaintext',

  // Embedded / Hardware
  ino: 'cpp',
  pde: 'cpp',
  hex: 'plaintext',
  bin: 'plaintext',
  elf: 'plaintext',
  map: 'plaintext',
  lst: 'plaintext',
  i: 'c',
  ii: 'cpp',

  // Math / Science
  mathematica: 'plaintext',
  nb: 'plaintext',
  wl: 'plaintext',
  wls: 'plaintext',
  matlab: 'plaintext',
  mlx: 'plaintext',
  octave: 'plaintext',
  scilab: 'plaintext',
  sce: 'plaintext',
  sci: 'plaintext',
  jupyter: 'json',
  sage: 'python',
  Rmd: 'markdown',

  // Regex / Grammar
  g4: 'plaintext',
  g: 'plaintext',
  y: 'plaintext',
  yacc: 'plaintext',
  lex: 'plaintext',
  l: 'plaintext',
  yy: 'plaintext',
  ll: 'plaintext',

  // Misc dev files
  browserslistrc: 'plaintext',
  nvmrc: 'plaintext',
  nodeversion: 'plaintext',
  pythonversion: 'plaintext',
  rubyversion: 'plaintext',
  javaversion: 'plaintext',
  sdkmanrc: 'plaintext',
  asdf: 'plaintext',
  toolversions: 'plaintext',
  direnv: 'plaintext',
  flake8: 'ini',
  pylint: 'ini',
  pylintrc: 'ini',
  bandit: 'ini',
  tox: 'ini',
  coverage: 'ini',
  coveragerc: 'ini',
  pydocstyle: 'ini',
  mypy: 'ini',
  isort: 'ini',
  black: 'plaintext',
  yapf: 'plaintext',
  autopep8: 'plaintext',
  prettierrc: 'json',
  prettierrcjson: 'json',
  prettierrcjs: 'javascript',
  prettierrcyaml: 'yaml',
  eslintrc: 'json',
  eslintrcjson: 'json',
  eslintrcjs: 'javascript',
  eslintrcyaml: 'yaml',
  babelrc: 'json',
  babelrcjson: 'json',
  babelrcjs: 'javascript',
  babelconfig: 'json',
  postcssrc: 'json',
  postcssconfig: 'javascript',
  tailwindrc: 'javascript',
  tailwindconfig: 'javascript',
  windirc: 'javascript',
  viterc: 'javascript',
  viteconfig: 'javascript',
  vitestconfig: 'javascript',
  rollupconfig: 'javascript',
  rolluprc: 'javascript',
  webpackrc: 'javascript',
  webpackconfig: 'javascript',
  tsconfig: 'json',
  tsconfigjson: 'json',
  jsconfig: 'json',
  jsconfigjson: 'json',
  manifestjson: 'json',
  packagejson: 'json',
  packagelock: 'json',
  npmshrinkwrap: 'json',
  yarnlock: 'plaintext',
  pnpmlock: 'yaml',
  pnpmworkspace: 'yaml',
  pnpmfile: 'javascript',
  lernajson: 'json',
  nx: 'json',
  turborepo: 'json',
  turbopack: 'json',
  changeset: 'plaintext',
  changesets: 'plaintext',
  allcontributorsrc: 'json',
  codeowners: 'plaintext',
  codacy: 'plaintext',
  codeclimate: 'plaintext',
  sonarcloud: 'plaintext',
  sonarqube: 'plaintext',
  snyk: 'plaintext',
  dependabot: 'yaml',
  renovate: 'json',
  mergify: 'yaml',
  stale: 'yaml',
  nojekyll: 'plaintext',
  CNAME: 'plaintext',
};

const FILENAME_MAP: Record<string, string> = {
  dockerfile: 'dockerfile',
  dockerfiledev: 'dockerfile',
  dockerfileprod: 'dockerfile',
  dockerfilelocal: 'dockerfile',
  makefile: 'plaintext',
  gnumakefile: 'plaintext',
  bsdmakefile: 'plaintext',
  cmake: 'plaintext',
  cmakelists: 'plaintext',
  vagrantfile: 'ruby',
  gemfile: 'ruby',
  rakefile: 'ruby',
  podfile: 'ruby',
  berksfile: 'ruby',
  capfile: 'ruby',
  guardfile: 'ruby',
  rake: 'ruby',
  brewfile: 'ruby',
  jenkinsfile: 'plaintext',
  jakefile: 'javascript',
  gruntfile: 'javascript',
  gulpfile: 'javascript',
  gulpfilejs: 'javascript',
  gulpfilets: 'typescript',
  webpackconfigjs: 'javascript',
  webpackconfigts: 'typescript',
  viteconfigjs: 'javascript',
  viteconfigts: 'typescript',
  vitestconfigjs: 'javascript',
  vitestconfigts: 'typescript',
  rollupconfigjs: 'javascript',
  rollupconfigts: 'typescript',
  postcssconfigjs: 'javascript',
  postcssconfigts: 'typescript',
  tailwindconfigjs: 'javascript',
  tailwindconfigts: 'typescript',
  babelconfigjs: 'javascript',
  babelconfigts: 'typescript',
  eslintrcjs: 'javascript',
  eslintrcts: 'typescript',
  prettierrcjs: 'javascript',
  prettierrcts: 'typescript',
  jsconfigjson: 'json',
  tsconfigjson: 'json',
  packagelockjson: 'json',
  yarnlock: 'plaintext',
  pnpmlockyaml: 'yaml',
  pnpmworkspaceyaml: 'yaml',
  lernajson: 'json',
  nxjson: 'json',
  '': 'plaintext',
  '.env': 'ini',
  '.envlocal': 'ini',
  '.envdevelopment': 'ini',
  '.envproduction': 'ini',
  '.envtest': 'ini',
  '.envstaging': 'ini',
  '.envdev': 'ini',
  '.envprod': 'ini',
  '.envsample': 'ini',
  '.envexample': 'ini',
  '.envtemplate': 'ini',
  '.envdefaults': 'ini',
  '.gitignore': 'plaintext',
  '.gitattributes': 'plaintext',
  '.gitmodules': 'plaintext',
  '.gitkeep': 'plaintext',
  '.dockerignore': 'plaintext',
  '.npmignore': 'plaintext',
  '.eslintignore': 'plaintext',
  '.prettierignore': 'plaintext',
  '.babelignore': 'plaintext',
  '.browserslistrc': 'plaintext',
  '.nvmrc': 'plaintext',
  '.nodeversion': 'plaintext',
  '.pythonversion': 'plaintext',
  '.rubyversion': 'plaintext',
  '.javaversion': 'plaintext',
  '.sdkmanrc': 'plaintext',
  '.toolversions': 'plaintext',
  '.direnv': 'plaintext',
  '.flake8': 'ini',
  '.pylintrc': 'ini',
  '.coveragerc': 'ini',
  '.mypyini': 'ini',
  '.isortcfg': 'ini',
  '.editorconfig': 'ini',
  '.npmrc': 'ini',
  '.yarnrc': 'ini',
  '.yarnrcyaml': 'yaml',
  '.yarnrcyml': 'yaml',
  '.pnpjs': 'javascript',
  '.pnp': 'javascript',
  '.prettierrc': 'json',
  '.eslintrc': 'json',
  '.babelrc': 'json',
  '.lintstagedrc': 'json',
  '.lintstagedrcjson': 'json',
  '.lintstagedrcjs': 'javascript',
  '.lintstagedrcyaml': 'yaml',
  '.lintstagedrcyml': 'yaml',
  '.huskyrc': 'json',
  '.huskyrcjson': 'json',
  '.huskyrcjs': 'javascript',
  '.commitlintrc': 'json',
  '.commitlintrcjson': 'json',
  '.commitlintrcjs': 'javascript',
  '.stylelintrc': 'json',
  '.stylelintrcjson': 'json',
  '.stylelintrcjs': 'javascript',
  '.stylelintignore': 'plaintext',
  '.remarkrc': 'json',
  '.rehyperc': 'json',
  '.markdownlintrc': 'json',
  '.htmlhintrc': 'json',
  '.csslintrc': 'json',
  '.jshintrc': 'json',
  '.jscsrc': 'json',
  '.jsbeautifyrc': 'json',
  '.csscombjson': 'json',
  '.csscomb': 'json',
  '.ternproject': 'json',
  '.ternconfig': 'json',
  '.watchmanconfig': 'json',
  '.flowconfig': 'ini',
  '.clangformat': 'yaml',
  '.clangtidy': 'yaml',
  '.clangd': 'yaml',
  '.gdbinit': 'plaintext',
  '.lldbinit': 'plaintext',
  '.gdb': 'plaintext',
  '.lldb': 'plaintext',
  '.vimrc': 'plaintext',
  '.gvimrc': 'plaintext',
  '.nvimrc': 'plaintext',
  '.exrc': 'plaintext',
  '.tmuxconf': 'plaintext',
  '.tmux': 'plaintext',
  '.screenrc': 'plaintext',
  '.inputrc': 'plaintext',
  '.bashrc': 'shell',
  '.bashprofile': 'shell',
  '.bashaliases': 'shell',
  '.bashlogout': 'shell',
  '.zshrc': 'shell',
  '.zprofile': 'shell',
  '.zlogin': 'shell',
  '.zlogout': 'shell',
  '.zshenv': 'shell',
  '.zshaliases': 'shell',
  '.zshfuncs': 'shell',
  '.zshhistory': 'plaintext',
  '.zshcompdump': 'plaintext',
  '.profile': 'shell',
  '.kshrc': 'shell',
  '.tcshrc': 'shell',
  '.cshrc': 'shell',
  '.login': 'shell',
  '.logout': 'shell',
  '.pam_environment': 'plaintext',
  '.xinitrc': 'shell',
  '.xsession': 'shell',
  '.xprofile': 'shell',
  '.Xresources': 'plaintext',
  '.Xdefaults': 'plaintext',
  '.xmodmap': 'plaintext',
  '.xbindkeysrc': 'plaintext',
  '.conkyrc': 'plaintext',
  '.i3config': 'plaintext',
  '.swayconfig': 'plaintext',
  '.qtileconfig': 'plaintext',
  '.awesomeconfig': 'plaintext',
  '.spectrwmconf': 'plaintext',
  '.dwmconfig': 'plaintext',
  '.bspwmrc': 'shell',
  '.sxhkdrc': 'plaintext',
  '.polybarconfig': 'plaintext',
  '.lemonbarconfig': 'plaintext',
  '.dunstrc': 'plaintext',
  '.comptonconf': 'plaintext',
  '.picomconf': 'plaintext',
  '.roficonfig': 'plaintext',
  '.alacrittyyml': 'yaml',
  '.alacrittyyaml': 'yaml',
  '.alacrittytoml': 'ini',
  '.kittyconf': 'plaintext',
  '.weztermlua': 'lua',
  '.styluayaml': 'yaml',
  '.luacheckrc': 'lua',
  '.luacov': 'lua',
  '.luac': 'plaintext',
  '.luarocks': 'plaintext',
  '.newsrc': 'plaintext',
  '.mailrc': 'plaintext',
  '.muttrc': 'plaintext',
  '.msmtprc': 'plaintext',
  '.mbsyncrc': 'plaintext',
  '.offlineimaprc': 'plaintext',
  '.notmuchconfig': 'plaintext',
  '.aercstylesets': 'plaintext',
  '.aercbinds': 'plaintext',
  '.newsboaturls': 'plaintext',
  '.newsboatconfig': 'plaintext',
  '.irssiconfig': 'plaintext',
  '.weechat': 'plaintext',
  '.zncconf': 'plaintext',
  '.bitlbee': 'plaintext',
  '.taskrc': 'plaintext',
  '.timewarrior': 'plaintext',
  '.vitconfig': 'plaintext',
  '.hgrc': 'ini',
  '.hgignore': 'plaintext',
  '.bzrignore': 'plaintext',
  '.cvsignore': 'plaintext',
  '.svnignore': 'plaintext',
  '.tfignore': 'plaintext',
  '.p4ignore': 'plaintext',
  '.slugignore': 'plaintext',
  '.upignore': 'plaintext',
  '.eleventyignore': 'plaintext',
  '.eleventyjs': 'javascript',
  '.gcloudignore': 'plaintext',
  '.cfignore': 'plaintext',
  '.ftppass': 'plaintext',
  '.netrc': 'plaintext',
  '.curlrc': 'plaintext',
  '.wgetrc': 'plaintext',
  '.aria2conf': 'plaintext',
  '.htpasswd': 'plaintext',
  '.htaccess': 'plaintext',
  '.nginxconf': 'plaintext',
  '.apacheconf': 'plaintext',
  '.certbot': 'plaintext',
  '.acmesh': 'plaintext',
  '. dehydrated': 'plaintext',
  '.sshconfig': 'plaintext',
  '.sshknownhosts': 'plaintext',
  '.sshfingerprints': 'plaintext',
  '.k5login': 'plaintext',
  '.k5users': 'plaintext',
  '.nfs': 'plaintext',
  '.afprc': 'plaintext',
  '.smbcredentials': 'plaintext',
  '.davfs2secrets': 'plaintext',
  '.rcloneconf': 'ini',
  '.restic': 'plaintext',
  '.borgmatic': 'yaml',
  '.duply': 'plaintext',
  '.duplicity': 'plaintext',
  '.rsyncfilter': 'plaintext',
  '.rsyncexclude': 'plaintext',
  '.unison': 'plaintext',
  '.syncthingconfig': 'json',
  '.keepassxc': 'plaintext',
  '.passwordstore': 'plaintext',
  '.gnupggpgconf': 'ini',
  '.gnupgscdaemonconf': 'ini',
  '.gnupgagentconf': 'ini',
  '.gnupgsshcontrol': 'plaintext',
  '.gnupgsecring': 'plaintext',
  '.gnupgpubring': 'plaintext',
  '.gnupgtrustdb': 'plaintext',
  '.gnupgopenpgprevocs': 'plaintext',
  '.gnupgdirmngr': 'plaintext',
  '.procmailrc': 'plaintext',
  '.fetchmailrc': 'plaintext',
  '.esmtprc': 'plaintext',
  '.mailfilter': 'plaintext',
  '.sieve': 'plaintext',
  '.dovecot': 'plaintext',
  '.postfix': 'plaintext',
  '.exim': 'plaintext',
  '.sendmail': 'plaintext',
  '.opendkim': 'plaintext',
  '.opendmarc': 'plaintext',
  '.spf': 'plaintext',
  '.dmarc': 'plaintext',
  '.dkim': 'plaintext',
  '.bind': 'plaintext',
  '.named': 'plaintext',
  '.zone': 'plaintext',
  '.unbound': 'plaintext',
  '.dnsmasq': 'plaintext',
  '.pdns': 'plaintext',
  '.kea': 'plaintext',
  '.dhcpd': 'plaintext',
  '.radvd': 'plaintext',
  '.nftables': 'plaintext',
  '.iptables': 'plaintext',
  '.ip6tables': 'plaintext',
  '.ebtables': 'plaintext',
  '.arptables': 'plaintext',
  '.ufw': 'plaintext',
  '.firewalld': 'plaintext',
  '.shorewall': 'plaintext',
  '.ferm': 'plaintext',
  '.ipset': 'plaintext',
  '.keepalived': 'plaintext',
  '.haproxycfg': 'plaintext',
  '.varnishdefaultvcl': 'plaintext',
  '.squidconf': 'plaintext',
  '.privoxy': 'plaintext',
  '.tinyproxy': 'plaintext',
  '.torrc': 'plaintext',
  '.i2pd': 'plaintext',
  '.ynh': 'plaintext',
  '.yunohost': 'plaintext',
  '.freedombox': 'plaintext',
  '.openwrt': 'plaintext',
  '.lede': 'plaintext',
  '.pfsense': 'plaintext',
  '.opnsense': 'plaintext',
  '.m0n0wall': 'plaintext',
  '.ipfire': 'plaintext',
  '.endian': 'plaintext',
  '.zeroshell': 'plaintext',
  '.clearos': 'plaintext',
  '.nethserver': 'plaintext',
  '.rockstor': 'plaintext',
  '.freenas': 'plaintext',
  '.truenas': 'plaintext',
  '.omv': 'plaintext',
  '.openmediavault': 'plaintext',
  '.unraid': 'plaintext',
  '.xpenology': 'plaintext',
  '.synology': 'plaintext',
  '.qnap': 'plaintext',
  '.asustor': 'plaintext',
  '.terramaster': 'plaintext',
  '.wdmycloud': 'plaintext',
  '.mybooklive': 'plaintext',
  '.readynas': 'plaintext',
  '.netgear': 'plaintext',
  '.dlink': 'plaintext',
  '.buffalo': 'plaintext',
  '.seagate': 'plaintext',
  '.hpe': 'plaintext',
  '.dell': 'plaintext',
  '.supermicro': 'plaintext',
  '.tyan': 'plaintext',
  '.asus': 'plaintext',
  '.gigabyte': 'plaintext',
  '.msi': 'plaintext',
  '.asrock': 'plaintext',
  '.intel': 'plaintext',
  '.amd': 'plaintext',
  '.nvidia': 'plaintext',
  '.arm': 'plaintext',
  '.raspberrypi': 'plaintext',
  '.pine64': 'plaintext',
  '.odroid': 'plaintext',
  '.bananapi': 'plaintext',
  '.nanopi': 'plaintext',
  '.orangepi': 'plaintext',
  '.librecomputer': 'plaintext',
  '.hardkernel': 'plaintext',
  '.friendlyelec': 'plaintext',
  '.radxa': 'plaintext',
  '.khadas': 'plaintext',
  '.pinebook': 'plaintext',
  '.clockworkpi': 'plaintext',
  '.gameshell': 'plaintext',
  '.devterm': 'plaintext',
  '.uconsole': 'plaintext',
  '.miyoo': 'plaintext',
  '.trimui': 'plaintext',
  '.anbernic': 'plaintext',
  '.powkiddy': 'plaintext',
  '.rg35xx': 'plaintext',
  '.rg40xx': 'plaintext',
  '.rg28xx': 'plaintext',
  '.rgcube': 'plaintext',
  '.rg556': 'plaintext',
  '.rk2023': 'plaintext',
  '.rgb10max3': 'plaintext',
  '.rgb30': 'plaintext',
  '.ogabe': 'plaintext',
  '.retroid': 'plaintext',
  '.ayn': 'plaintext',
  '.gpd': 'plaintext',
  '.onexplayer': 'plaintext',
  '.ayaneo': 'plaintext',
  '.steamdeck': 'plaintext',
  '.ally': 'plaintext',
  '.legiongo': 'plaintext',
  '.msteam': 'plaintext',
  '.playstation': 'plaintext',
  '.xbox': 'plaintext',
  '.nintendo': 'plaintext',
  '.switch': 'plaintext',
  '.wii': 'plaintext',
  '.wiiu': 'plaintext',
  '.3ds': 'plaintext',
  '.ds': 'plaintext',
  '.gba': 'plaintext',
  '.gbc': 'plaintext',
  '.gb': 'plaintext',
  '.n64': 'plaintext',
  '.snes': 'plaintext',
  '.nes': 'plaintext',
  '.gamecube': 'plaintext',
  '.dreamcast': 'plaintext',
  '.saturn': 'plaintext',
  '.megadrive': 'plaintext',
  '.genesis': 'plaintext',
  '.mastersystem': 'plaintext',
  '.segacd': 'plaintext',
  '.32x': 'plaintext',
  '.neogeo': 'plaintext',
  '.neogeocd': 'plaintext',
  '.neogeopocket': 'plaintext',
  '.wonderswan': 'plaintext',
  '.pcengine': 'plaintext',
  '.turbografx': 'plaintext',
  '.msx': 'plaintext',
  '.atari': 'plaintext',
  '.amiga': 'plaintext',
  '.c64': 'plaintext',
  '.vic20': 'plaintext',
  '.pet': 'plaintext',
  '.plus4': 'plaintext',
  '.c128': 'plaintext',
  '.zx': 'plaintext',
  '.spectrum': 'plaintext',
  '.ql': 'plaintext',
  '.samcoupe': 'plaintext',
  '.dragon': 'plaintext',
  '.trs80': 'plaintext',
  '.coco': 'plaintext',
  '.oric': 'plaintext',
  '.acorn': 'plaintext',
  '.bbc': 'plaintext',
  '.electron': 'plaintext',
  '.archimedes': 'plaintext',
  '.riscos': 'plaintext',
  '.bbcmicro': 'plaintext',
  '.cpc': 'plaintext',
  '.thomson': 'plaintext',
  '.to7': 'plaintext',
  '.mo5': 'plaintext',
  '.alice': 'plaintext',
  '.vg5000': 'plaintext',
  '.exl100': 'plaintext',
  '.mxs': 'plaintext',
  '.svi': 'plaintext',
  '.sc3000': 'plaintext',
  '.sf7000': 'plaintext',
  '.sg1000': 'plaintext',
  '.markiii': 'plaintext',
  '.sms': 'plaintext',
  '.gg': 'plaintext',
  '.pico': 'plaintext',
  '.tic80': 'plaintext',
  '.wasm4': 'plaintext',
  '.uxn': 'plaintext',
  '.cat': 'plaintext',
  '.dol': 'plaintext',
  '.elf': 'plaintext',
  '.nro': 'plaintext',
  '.nso': 'plaintext',
  '.nca': 'plaintext',
  '.nsp': 'plaintext',
  '.xci': 'plaintext',
  '.ncz': 'plaintext',
  '.nsz': 'plaintext',
  '.xcz': 'plaintext',
  '.nut': 'plaintext',
  '.gm81': 'plaintext',
  '.gms': 'plaintext',
  '.yyp': 'plaintext',
  '.yy': 'plaintext',
  '.gml': 'plaintext',
  '.dnd': 'plaintext',
  '.shader': 'plaintext',
  '.cginc': 'plaintext',
  '.cg': 'plaintext',
  '.hlsl': 'plaintext',
  '.fx': 'plaintext',
  '.fxh': 'plaintext',
  '.usf': 'plaintext',
  '.ush': 'plaintext',
  '.compute': 'plaintext',
  '.raytrace': 'plaintext',
  '.tesc': 'plaintext',
  '.tese': 'plaintext',
  '.geom': 'plaintext',
  '.frag': 'plaintext',
  '.vert': 'plaintext',
  '.glsl': 'plaintext',
  '.glslv': 'plaintext',
  '.glslf': 'plaintext',
  '.vsh': 'plaintext',
  '.fsh': 'plaintext',
  '.metal': 'plaintext',
  '.msl': 'plaintext',
  '.air': 'plaintext',
  '.metallib': 'plaintext',
  '.nvvm': 'plaintext',
  '.ptx': 'plaintext',
  '.sass': 'plaintext',
  '.maxas': 'plaintext',
  '.cubin': 'plaintext',
  '.fatbin': 'plaintext',
  '.opencl': 'plaintext',
  '.cl': 'plaintext',
  '.sycl': 'plaintext',
  '.dpcpp': 'plaintext',
  '.oneapi': 'plaintext',
  '.rocm': 'plaintext',
  '.hip': 'plaintext',
  '.hsaco': 'plaintext',
  '.gcn': 'plaintext',
  '.rdna': 'plaintext',
  '.cdna': 'plaintext',
  '.spirv': 'plaintext',
  '.spvasm': 'plaintext',
  '.ll': 'plaintext',
  '.bc': 'plaintext',
  '.mlir': 'plaintext',
  '.tflite': 'plaintext',
  '.onnx': 'plaintext',
  '.pb': 'plaintext',
  '.pbtxt': 'plaintext',
  '.savedmodel': 'plaintext',
  '.checkpoint': 'plaintext',
  '.ckpt': 'plaintext',
  '.safetensors': 'plaintext',
  '.gguf': 'plaintext',
  '.ggml': 'plaintext',
  '.pt': 'plaintext',
  '.pth': 'plaintext',
  '.pkl': 'plaintext',
  '.pickle': 'plaintext',
  '.joblib': 'plaintext',
  '.npy': 'plaintext',
  '.npz': 'plaintext',
  '.h5': 'plaintext',
  '.hdf5': 'plaintext',
  '.caffemodel': 'plaintext',
  '.prototxt': 'plaintext',
  '.weights': 'plaintext',
  '.darknet': 'plaintext',
  '.cfg': 'ini',
  '.ini': 'ini',
  '.toml': 'ini',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.json': 'json',
  '.xml': 'xml',
  '.csv': 'plaintext',
  '.tsv': 'plaintext',
  '.sql': 'sql',
  '.sqlite': 'sql',
  '.db': 'plaintext',
  '.mdb': 'plaintext',
  '.accdb': 'plaintext',
  '.dbf': 'plaintext',
  '.fdb': 'plaintext',
  '.adb': 'plaintext',
  '.ads': 'plaintext',
};

export function getLanguageFromPath(filePath: string): string {
  const parts = filePath.split('/');
  const filename = parts[parts.length - 1];
  const lowerName = filename.toLowerCase();

  // Check exact filename match first
  if (FILENAME_MAP[lowerName]) {
    return FILENAME_MAP[lowerName];
  }

  // Handle Dockerfile variants (e.g., Dockerfile.dev)
  if (lowerName.startsWith('dockerfile')) {
    return 'dockerfile';
  }

  // Handle Makefile variants
  if (lowerName.includes('makefile')) {
    return 'plaintext';
  }

  // .env variants
  if (lowerName.startsWith('.env')) {
    return 'ini';
  }

  // Extension based
  const ext = lowerName.split('.').pop() || '';
  return EXTENSION_MAP[ext] || 'plaintext';
}

// ───────────────────────────────────────────────
// Image / Media Detection
// ───────────────────────────────────────────────

const IMAGE_EXTENSIONS = new Set([
  // Raster
  'png', 'jpg', 'jpeg', 'gif', 'webp', 'bmp', 'ico', 'tiff', 'tif', 'avif', 'heic', 'heif',
  'jfif', 'pjpeg', 'pjp', 'apng', 'jxr', 'hdp', 'wdp', 'cur', 'dds', 'exr', 'hdr',
  'jpg2', 'j2k', 'jpf', 'jpx', 'jpm', 'mj2', 'pcx', 'pbm', 'pgm', 'ppm', 'pnm', 'qoi',
  'sgi', 'tga', 'icb', 'vda', 'vst', 'xbm', 'xpm',
  // Raw photo
  '3fr', 'arw', 'crw', 'cr2', 'cr3', 'dcr', 'dng', 'erf', 'kdc', 'mef', 'mos', 'mrw',
  'nef', 'nrw', 'orf', 'pef', 'raf', 'rw2', 'sr2', 'srf', 'srw', 'x3f',
  // macOS icon
  'icns',
]);

export function isImageFile(filePath: string): boolean {
  const ext = filePath.split('.').pop()?.toLowerCase() || '';
  return IMAGE_EXTENSIONS.has(ext);
}

export function isSvgFile(filePath: string): boolean {
  const ext = filePath.split('.').pop()?.toLowerCase() || '';
  return ext === 'svg';
}

const BINARY_EXTENSIONS = new Set([
  // Archives
  'zip', 'tar', 'tgz', 'gz', 'bz2', 'xz', '7z', 'rar', 'deb', 'rpm', 'pkg', 'dmg',
  // Executables / Libraries
  'exe', 'dll', 'so', 'dylib', 'bin', 'o', 'a', 'lib', 'out', 'wasm',
  // Audio
  'mp3', 'wav', 'ogg', 'oga', 'flac', 'aac', 'wma', 'm4a', 'opus',
  // Video
  'mp4', 'avi', 'mov', 'mkv', 'wmv', 'flv', 'webm', 'm4v', 'mpg', 'mpeg',
  // Fonts
  'ttf', 'otf', 'woff', 'woff2', 'eot',
  // Documents
  'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'ods', 'odp',
  // Images already handled by isImageFile
]);

export function isBinaryFile(filePath: string): boolean {
  const ext = filePath.split('.').pop()?.toLowerCase() || '';
  return BINARY_EXTENSIONS.has(ext);
}

// ───────────────────────────────────────────────
// MIME Type Map
// ───────────────────────────────────────────────

const MIME_TYPE_MAP: Record<string, string> = {
  // Images
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  jfif: 'image/jpeg',
  pjpeg: 'image/jpeg',
  pjp: 'image/jpeg',
  gif: 'image/gif',
  webp: 'image/webp',
  bmp: 'image/bmp',
  ico: 'image/x-icon',
  cur: 'image/x-icon',
  tiff: 'image/tiff',
  tif: 'image/tiff',
  avif: 'image/avif',
  heic: 'image/heic',
  heif: 'image/heif',
  apng: 'image/apng',
  jxr: 'image/vnd.ms-photo',
  hdp: 'image/vnd.ms-photo',
  wdp: 'image/vnd.ms-photo',
  dds: 'image/vnd.ms-dds',
  exr: 'image/x-exr',
  hdr: 'image/vnd.radiance',
  jpg2: 'image/jp2',
  j2k: 'image/jp2',
  jpf: 'image/jp2',
  jpx: 'image/jp2',
  jpm: 'image/jpm',
  mj2: 'image/jp2',
  pcx: 'image/x-pcx',
  pbm: 'image/x-portable-bitmap',
  pgm: 'image/x-portable-graymap',
  ppm: 'image/x-portable-pixmap',
  pnm: 'image/x-portable-anymap',
  qoi: 'image/qoi',
  sgi: 'image/sgi',
  tga: 'image/x-targa',
  icb: 'image/x-targa',
  vda: 'image/x-targa',
  vst: 'image/x-targa',
  xbm: 'image/x-xbitmap',
  xpm: 'image/x-xpixmap',
  svg: 'image/svg+xml',
  icns: 'image/x-icns',
  // Raw
  '3fr': 'image/x-fuji-raf',
  arw: 'image/x-sony-arw',
  crw: 'image/x-canon-crw',
  cr2: 'image/x-canon-cr2',
  cr3: 'image/x-canon-cr3',
  dcr: 'image/x-kodak-dcr',
  dng: 'image/x-adobe-dng',
  erf: 'image/x-epson-erf',
  kdc: 'image/x-kodak-kdc',
  mef: 'image/x-mamiya-mef',
  mos: 'image/x-leaf-mos',
  mrw: 'image/x-minolta-mrw',
  nef: 'image/x-nikon-nef',
  nrw: 'image/x-nikon-nrw',
  orf: 'image/x-olympus-orf',
  pef: 'image/x-pentax-pef',
  raf: 'image/x-fuji-raf',
  rw2: 'image/x-panasonic-rw2',
  sr2: 'image/x-sony-sr2',
  srf: 'image/x-sony-srf',
  srw: 'image/x-samsung-srw',
  x3f: 'image/x-sigma-x3f',
  // Documents
  pdf: 'application/pdf',
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  dot: 'application/msword',
  dotx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
  xls: 'application/vnd.ms-excel',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  xlsm: 'application/vnd.ms-excel.sheet.macroEnabled.12',
  xlsb: 'application/vnd.ms-excel.sheet.binary.macroEnabled.12',
  xltx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
  ppt: 'application/vnd.ms-powerpoint',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  potx: 'application/vnd.openxmlformats-officedocument.presentationml.template',
  ppsx: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
  odt: 'application/vnd.oasis.opendocument.text',
  ods: 'application/vnd.oasis.opendocument.spreadsheet',
  odp: 'application/vnd.oasis.opendocument.presentation',
  rtf: 'application/rtf',
  txt: 'text/plain',
  text: 'text/plain',
  md: 'text/markdown',
  markdown: 'text/markdown',
  ics: 'text/calendar',
  vcf: 'text/vcard',
  // Audio
  mp3: 'audio/mpeg',
  wav: 'audio/wav',
  ogg: 'audio/ogg',
 oga: 'audio/ogg',
  flac: 'audio/flac',
  aac: 'audio/aac',
  wma: 'audio/x-ms-wma',
  m4a: 'audio/mp4',
  aiff: 'audio/aiff',
  au: 'audio/basic',
  mid: 'audio/midi',
  midi: 'audio/midi',
  opus: 'audio/opus',
  weba: 'audio/webm',
  // Video
  mp4: 'video/mp4',
  m4v: 'video/mp4',
  mov: 'video/quicktime',
  qt: 'video/quicktime',
  avi: 'video/x-msvideo',
  mkv: 'video/x-matroska',
  wmv: 'video/x-ms-wmv',
  flv: 'video/x-flv',
  webm: 'video/webm',
  ogv: 'video/ogg',
  '3gp': 'video/3gpp',
  '3g2': 'video/3gpp2',
  mpeg: 'video/mpeg',
  mpg: 'video/mpeg',
  ts: 'video/mp2t',
  // Archives
  zip: 'application/zip',
  tar: 'application/x-tar',
  gz: 'application/gzip',
  tgz: 'application/gzip',
  bz2: 'application/x-bzip2',
  xz: 'application/x-xz',
  txz: 'application/x-xz',
  '7z': 'application/x-7z-compressed',
  rar: 'application/vnd.rar',
  cab: 'application/vnd.ms-cab-compressed',
  iso: 'application/x-iso9660-image',
  dmg: 'application/x-apple-diskimage',
  deb: 'application/vnd.debian.binary-package',
  rpm: 'application/x-rpm',
  jar: 'application/java-archive',
  war: 'application/java-archive',
  ear: 'application/java-archive',
  // Fonts
  woff: 'font/woff',
  woff2: 'font/woff2',
  ttf: 'font/ttf',
  otf: 'font/otf',
  eot: 'application/vnd.ms-fontobject',
  // Code / Data
  json: 'application/json',
  xml: 'application/xml',
  yaml: 'application/yaml',
  yml: 'application/yaml',
  csv: 'text/csv',
  tsv: 'text/tab-separated-values',
  sql: 'application/sql',
  js: 'text/javascript',
  mjs: 'text/javascript',
  cjs: 'text/javascript',
  tsx: 'text/typescript-jsx',
  css: 'text/css',
  html: 'text/html',
  htm: 'text/html',
  wasm: 'application/wasm',
  // Misc
  exe: 'application/x-msdownload',
  dll: 'application/x-msdownload',
  so: 'application/x-sharedlib',
  dylib: 'application/x-dylib',
  bin: 'application/octet-stream',
  dat: 'application/octet-stream',
};

export function getMimeType(filePath: string): string {
  const ext = filePath.split('.').pop()?.toLowerCase() || '';
  return MIME_TYPE_MAP[ext] || 'application/octet-stream';
}
